#! /bin/sh
arm-none-eabi-gcc -O2 -mfpu=vfp -mfloat-abi=hard -march=armv6zk -mtune=arm1176jzf-s -nostartfiles -g -Wl,-verbose -Wl,-T,rpi.x kernel.c -o kernel.elf

#-none-eabi-gcc -O2 -mfpu=vfp -mfloat-abi=hard -march=armv6zk -mtune=arm1176jzf-s -nostartfiles -g kernel.c -o kernel.elf

arm-none-eabi-objcopy kernel.elf -O binary kernel.img
