#! /bin/bash

sudo make clean all
clear

read -p "How many frequencies are you testing? " freq
read -p "Enter sampling frequency: " sample
read -p "Enter # of points: " points

i=1
while [ $i -le $freq ]
do
    i=$(($i+1))
    read -p "Enter output file name: " file
    
    sudo .././capture sample points file
    
done